### ISSUE TITLE
solving other difficulty levels 

### ISSUE THREAD

**Issue by TontonTremblay** [violin-anderson/KabufudaSolitaireBot#1]
Hey cool project, I love the applications. 

I am trying to hack to be able to solve the other difficulties, since they are a subset of expert. I was able to get the click to medium, but then the game does get solve, solver finds a solution but the execution does not work, do you have an idea?

**Comment by violin-anderson** [comment]
Not sure. Was it working before you changed it to click on medium?

**Comment by TontonTremblay** [comment]
Non it was not.

**Comment by TontonTremblay** [comment]
I hope this works, https://web.microsoftstream.com/video/8e5dc930-dd65-4242-a0e9-f6a3fb5852eb Here is the behaviour.

**Comment by violin-anderson** [comment]
I'm not able to view that video, sorry. Can you first make sure you followed all the steps in the README exactly? If that doesn't help, can you describe the behavior to me? If it's moving so fast that you can't tell what's happening, try increasing guilib.PAUSE on line 42 in main.py. That's how long in seconds it waits after each click. Setting it to about 0.5 should make it easy to see what's going on

**Comment by Tylian83** [comment]
Hey,
I have the same problem with the "medium" difficulty.
I increase the time between each click in this video if you want to check. I'm not sure what is happening ..
https://www.youtube.com/watch?v=dNV_hzx6USM

The error trace i've got : 

```
Current Depth: 50 Stack Length: 87
Solution Found
Current Depth: 51 Stack Length: 86
Current Depth: 51 Stack Length: 86
['xtpww', '8ptry', 'krdrk', 'to8rk', 't8xd8', 'pryok', 'wdoyy', 'xykyd']
Traceback (most recent call last):
  File "P:\Kabufuda solver\main.py", line 60, in <module>
    main()
  File "P:\Kabufuda solver\main.py", line 55, in main
    sln = solve.solveGame(board)
  File "P:\Kabufuda solver\solve.py", line 284, in solveGame
    verifyGame(gl)
  File "P:\Kabufuda solver\solve.py", line 249, in verifyGame
    assert(allList.count(c) == DUPES)
AssertionError
```

**Comment by violin-anderson** [comment]
@Tylian83 Based on the video you sent, it appears the game window is losing focus before the bot executes the first click. That means the first click focuses on the game window but doesn't pick up a card as it should. From there, everything is out of sync and the bot isn't smart enough to realize it.

Make sure the game window has focus before the bot makes its first click, and try again. You might have to double check any modifications you made to the code. If you're trying to make it solve the currently shown puzzle and not start a new game, you have to comment out lines 45-51 in main.py
